name: CI/CD for Dev Branch

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    
        
    env:
      AUTH_SERVICE_PORT: ${{ secrets.AUTH_SERVICE_PORT }}
      USER_SERVICE_PORT: ${{ secrets.USER_SERVICE_PORT }}
      ROOM_SERVICE_PORT: ${{ secrets.ROOM_SERVICE_PORT }}
      DB_URL: ${{ secrets.DB_URL }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
      GRPC_PORT: ${{ secrets.GRPC_PORT }}
      ROOM_GRPC_PORT: ${{ secrets.ROOM_GRPC_PORT }}
    - name: Log Environment Variables
      run: |
        echo "DB_URL: $DB_URL"
        echo "JWT_SECRET_KEY: $JWT_SECRET_KEY"
        echo "GRPC_PORT: $GRPC_PORT"
        # Add more environment variables as needed
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: Install dependencies
      run: npm install
      
    - name: Run tests
      run: npm start
      
    - name: Build and deploy
      run: |
        npm run build
        # Add deployment steps here, e.g., deploying to a server or cloud platform
