name: CI/CD for Dev Branch

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21'
        
    - name: Install dependencies
      run: npm install
      
    - name: Run tests
      run: npm start

    # - name: Run lint
    #   run: npm lint
      
    - name: Build and deploy
      run: |
        npm run build
        # Add deployment steps here, e.g., deploying to a server or cloud platform
